-- Loosen posture, expression and gesture calibration so typical deliveries
-- reach good scores more easily. Widens TargetBand tolerances and lowers
-- FloorBand floors/ideals across every archetype. Superseded expression-only
-- recalibration from 202607210002.
insert into public.archetype_configs (archetype_key, version, scoring_config) values
  ('corporate_board', 1, '{"eye_contact":{"kind":"floor","low":0.35,"ideal":0.80},"expression":{"kind":"target","ideal":0.12,"tol_low":0.22,"tol_high":0.60},"posture":{"kind":"floor","low":0.15,"ideal":0.55},"gesture_frequency":{"kind":"target","ideal":0.25,"tol_low":0.45,"tol_high":0.85},"gesture_range":{"kind":"target","ideal":0.20,"tol_low":0.40,"tol_high":0.80},"openness":{"kind":"floor","low":0.12,"ideal":0.40},"smile_naturalness":{"kind":"floor","low":0.15,"ideal":0.65},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.75},"spatial_use":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.55},"gesture_freq_weight":0.60}'::jsonb),
  ('motivational_keynote', 1, '{"eye_contact":{"kind":"floor","low":0.25,"ideal":0.65},"expression":{"kind":"floor","low":0.02,"ideal":0.14},"posture":{"kind":"floor","low":0.12,"ideal":0.50},"gesture_frequency":{"kind":"target","ideal":0.70,"tol_low":0.90,"tol_high":0.90},"gesture_range":{"kind":"target","ideal":0.75,"tol_low":0.90,"tol_high":0.85},"openness":{"kind":"floor","low":0.12,"ideal":0.45},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.75},"movement_purposefulness":{"kind":"floor","low":0.25,"ideal":0.80},"spatial_use":{"kind":"floor","low":0.10,"ideal":0.65},"gesture_freq_weight":0.40}'::jsonb),
  ('startup_pitch', 1, '{"eye_contact":{"kind":"floor","low":0.30,"ideal":0.72},"expression":{"kind":"floor","low":0.02,"ideal":0.12},"posture":{"kind":"floor","low":0.15,"ideal":0.55},"gesture_frequency":{"kind":"target","ideal":0.50,"tol_low":0.75,"tol_high":0.85},"gesture_range":{"kind":"target","ideal":0.50,"tol_low":0.75,"tol_high":0.85},"openness":{"kind":"floor","low":0.12,"ideal":0.42},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.30,"ideal":0.82},"spatial_use":{"kind":"target","ideal":0.45,"tol_low":0.40,"tol_high":0.45},"gesture_freq_weight":0.50}'::jsonb),
  ('academic_conference', 1, '{"eye_contact":{"kind":"floor","low":0.25,"ideal":0.60},"expression":{"kind":"target","ideal":0.14,"tol_low":0.24,"tol_high":0.65},"posture":{"kind":"floor","low":0.15,"ideal":0.55},"gesture_frequency":{"kind":"target","ideal":0.35,"tol_low":0.60,"tol_high":0.85},"gesture_range":{"kind":"target","ideal":0.30,"tol_low":0.55,"tol_high":0.82},"openness":{"kind":"floor","low":0.10,"ideal":0.38},"smile_naturalness":{"kind":"floor","low":0.10,"ideal":0.55},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.72},"spatial_use":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.50},"gesture_freq_weight":0.55}'::jsonb),
  ('informal_team', 1, '{"eye_contact":{"kind":"floor","low":0.20,"ideal":0.55},"expression":{"kind":"floor","low":0.02,"ideal":0.13},"posture":{"kind":"floor","low":0.10,"ideal":0.45},"gesture_frequency":{"kind":"target","ideal":0.50,"tol_low":0.80,"tol_high":0.95},"gesture_range":{"kind":"target","ideal":0.50,"tol_low":0.80,"tol_high":0.95},"openness":{"kind":"floor","low":0.10,"ideal":0.42},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.15,"ideal":0.65},"spatial_use":{"kind":"floor","low":0.10,"ideal":0.55},"gesture_freq_weight":0.50}'::jsonb),
  ('job_interview', 1, '{"eye_contact":{"kind":"floor","low":0.35,"ideal":0.78},"expression":{"kind":"target","ideal":0.12,"tol_low":0.22,"tol_high":0.60},"posture":{"kind":"floor","low":0.18,"ideal":0.58},"gesture_frequency":{"kind":"target","ideal":0.30,"tol_low":0.55,"tol_high":0.82},"gesture_range":{"kind":"target","ideal":0.25,"tol_low":0.50,"tol_high":0.80},"openness":{"kind":"floor","low":0.15,"ideal":0.42},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.70},"spatial_use":{"kind":"target","ideal":0.15,"tol_low":0.15,"tol_high":0.45},"gesture_freq_weight":0.60}'::jsonb)
on conflict (archetype_key, version) do update
set scoring_config = excluded.scoring_config;
