-- Backfill complete scoring presets for databases created before every
-- supported archetype had a populated configuration.
insert into public.archetype_configs (archetype_key, version, scoring_config) values
  ('corporate_board', 1, '{"eye_contact":{"kind":"floor","low":0.35,"ideal":0.80},"expression":{"kind":"target","ideal":0.12,"tol_low":0.12,"tol_high":0.35},"posture":{"kind":"floor","low":0.45,"ideal":0.90},"gesture_frequency":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.45},"gesture_range":{"kind":"target","ideal":0.20,"tol_low":0.20,"tol_high":0.40},"openness":{"kind":"floor","low":0.30,"ideal":0.65},"smile_naturalness":{"kind":"floor","low":0.15,"ideal":0.65},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.75},"spatial_use":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.55},"gesture_freq_weight":0.60}'::jsonb),
  ('motivational_keynote', 1, '{"eye_contact":{"kind":"floor","low":0.25,"ideal":0.65},"expression":{"kind":"floor","low":0.03,"ideal":0.25},"posture":{"kind":"floor","low":0.40,"ideal":0.85},"gesture_frequency":{"kind":"target","ideal":0.70,"tol_low":0.55,"tol_high":0.50},"gesture_range":{"kind":"target","ideal":0.75,"tol_low":0.55,"tol_high":0.45},"openness":{"kind":"floor","low":0.35,"ideal":0.80},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.75},"movement_purposefulness":{"kind":"floor","low":0.25,"ideal":0.80},"spatial_use":{"kind":"floor","low":0.10,"ideal":0.65},"gesture_freq_weight":0.40}'::jsonb),
  ('startup_pitch', 1, '{"eye_contact":{"kind":"floor","low":0.30,"ideal":0.72},"expression":{"kind":"floor","low":0.03,"ideal":0.20},"posture":{"kind":"floor","low":0.45,"ideal":0.88},"gesture_frequency":{"kind":"target","ideal":0.50,"tol_low":0.40,"tol_high":0.45},"gesture_range":{"kind":"target","ideal":0.50,"tol_low":0.40,"tol_high":0.45},"openness":{"kind":"floor","low":0.35,"ideal":0.75},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.30,"ideal":0.82},"spatial_use":{"kind":"target","ideal":0.45,"tol_low":0.40,"tol_high":0.45},"gesture_freq_weight":0.50}'::jsonb),
  ('academic_conference', 1, '{"eye_contact":{"kind":"floor","low":0.25,"ideal":0.60},"expression":{"kind":"target","ideal":0.14,"tol_low":0.14,"tol_high":0.40},"posture":{"kind":"floor","low":0.45,"ideal":0.88},"gesture_frequency":{"kind":"target","ideal":0.35,"tol_low":0.30,"tol_high":0.45},"gesture_range":{"kind":"target","ideal":0.30,"tol_low":0.28,"tol_high":0.42},"openness":{"kind":"floor","low":0.25,"ideal":0.60},"smile_naturalness":{"kind":"floor","low":0.10,"ideal":0.55},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.72},"spatial_use":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.50},"gesture_freq_weight":0.55}'::jsonb),
  ('informal_team', 1, '{"eye_contact":{"kind":"floor","low":0.20,"ideal":0.55},"expression":{"kind":"floor","low":0.03,"ideal":0.22},"posture":{"kind":"floor","low":0.35,"ideal":0.78},"gesture_frequency":{"kind":"target","ideal":0.50,"tol_low":0.45,"tol_high":0.55},"gesture_range":{"kind":"target","ideal":0.50,"tol_low":0.45,"tol_high":0.55},"openness":{"kind":"floor","low":0.30,"ideal":0.75},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.15,"ideal":0.65},"spatial_use":{"kind":"floor","low":0.10,"ideal":0.55},"gesture_freq_weight":0.50}'::jsonb),
  ('job_interview', 1, '{"eye_contact":{"kind":"floor","low":0.35,"ideal":0.78},"expression":{"kind":"target","ideal":0.12,"tol_low":0.12,"tol_high":0.35},"posture":{"kind":"floor","low":0.50,"ideal":0.90},"gesture_frequency":{"kind":"target","ideal":0.30,"tol_low":0.28,"tol_high":0.42},"gesture_range":{"kind":"target","ideal":0.25,"tol_low":0.25,"tol_high":0.40},"openness":{"kind":"floor","low":0.30,"ideal":0.65},"smile_naturalness":{"kind":"floor","low":0.20,"ideal":0.70},"movement_purposefulness":{"kind":"floor","low":0.20,"ideal":0.70},"spatial_use":{"kind":"target","ideal":0.15,"tol_low":0.15,"tol_high":0.45},"gesture_freq_weight":0.60}'::jsonb)
on conflict (archetype_key, version) do update
set scoring_config = excluded.scoring_config;
